[package]
name = "nia_events"
version = "0.1.0"
authors = ["mirai"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.9.0"
evdev-rs = "0.3.1"
lazy_static = "1.4.0"
